Feat/registration page
VadimShkedov/hospitalFrontend pull request #1
Opened 2023-12-28 14:45 UTC by VadimShkedov

2023-12-29 08:28 UTC, baklanovairina requested changes

2023-12-29 08:28 UTC, baklanovairina commented on src/App.jsx
> +
лишняя пустая строка

2023-12-29 08:28 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +
лишняя пустая строка

2023-12-29 08:28 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +import registrationRequest from "../../../service/registration";
порядок импортов нарушен

2023-12-29 08:28 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +    } catch (error) {
тут что то не законченно
и try/catch в компонентах точно не будет
он же в редаксе будет, там где вызов сервисов

2023-12-29 08:28 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +      <Content>
ну не Content, поработай еще над неймингом

2023-12-29 08:28 UTC, baklanovairina commented on src/components/Registration/Form/index.jsx
> +      <Input placeholder="Логин" id="login" />
у тебя формы будут отличаться количеством полей, поэтому инпуты точно лучше убрать из этого компонента и передавать чилдренами

и создай такой Input, чтобы он уже поддерживал label и его можно было передать пропсом

2023-12-29 08:28 UTC, baklanovairina commented on src/components/Registration/Form/index.jsx
> +      <Button>Зарегистрироваться</Button>
ссылки не хватает на авторизацию

2023-12-29 08:28 UTC, baklanovairina commented on src/components/RegistrationForm/index.jsx
> +    <Form>
че то я не поняла, это вторая форма?? Зачем?
создай 1 которую можно переиспользовать и уже ее вызывай на странице регистрации

2023-12-29 08:28 UTC, baklanovairina commented on src/components/UI/Input.js
> +import styled from "styled-components";
а где сами компоненты?
Только стили подряд идут, и даже папок нет для компонетов

2023-12-29 08:28 UTC, baklanovairina commented on src/helpers/authValidation.js
> +const isLoginValid = (login) => {
слишком много конкретики, это же переиспользуемые функции, они могут использовать не только для валидации в регистрации или авторизации, поэтому меняй нейминг файла, функций и переменных

2023-12-29 08:28 UTC, baklanovairina commented on src/http/index.js
> +const BASE_URL = "http://localhost:5000"
это константа, выноси в файл с константами

2023-12-29 08:28 UTC, baklanovairina commented on src/index.jsx
> +    <App />
роута нет

2024-01-09 07:49 UTC, baklanovairina requested changes

2024-01-09 07:49 UTC, baklanovairina commented on src/Router.jsx
> +const router = () => createBrowserRouter([
роуты пишутся в App.js 
не создается для этого отдельный компонент

2024-01-09 07:49 UTC, baklanovairina commented on src/components/AuthForm/constants.js
> +export const authFormConstants = {
зачем эта интересная константа?

и что она делает внутри папки компоненты?

2024-01-09 07:49 UTC, baklanovairina commented on src/components/AuthForm/index.jsx
> +import { useRef } from "react";
src/components/AuthForm/index.jsx
почему AuthForm? Эта переиспоьзуемая форма, она может использоваться для чего угодно, а не только для авторизации или регистрации

2024-01-09 07:49 UTC, baklanovairina commented on src/components/AuthForm/index.jsx
> +import { useRef } from "react";
зачем здесь useRef? Это излишне, легко можно без него обойтись
Более того, он тебе усложняет переиспользование компонента

2024-01-09 07:49 UTC, baklanovairina commented on src/components/AuthForm/index.jsx
> +        <RightFooter>
странное название? Это вроде как не футер

2024-01-09 07:49 UTC, baklanovairina commented on src/components/AuthForm/styles.js
> +
не делай пожалуйста, по 2 пустые строки между стилями, достаточно одной

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +import { stringInputValidation, stringPasswordValidation } from "../../../helpers/validation";
порядок импортов нарушен

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +  const validateForm = async () => {
зачем здесь async
без await он все равно бессмысленные здесь

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +      setWarningMessage("Пароли не совпадают");
с чего вдруг с проверки паролей начали? Сначала логин

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +    dispatch(registration(
давай сделаем умнее, чтобы не импортить useDispatch
создай кастомынй хук useActions:

```
const useActions = () => {
  const dispatch = useDispatch();
  return bindActionCreators(AllActionCreators, dispatch);
};
```
где AllActionCreators - это все action-creators
и уже useActions импортируй сюда:
const { registration } = useActions();

а в этой функции будет 
registration(login, password)
и коллбэк функцию точно сюда передавать не нужно

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +        <h1>Зарегистрироваться в системе</h1>
не забудь, что тебе это нужно реализовать через контекст (по ТЗ)

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +          isRegistration
как выше писала, ты должен создать переиспользуемую формы для всего, а не только регистрации/авторизации, поэтому этот пропс лишний

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +          validateForm={validateForm}
тоже не зачем передавать функцию валидации, достаточно текста ошибки

2024-01-09 07:49 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +          errorMessage={warningMessage}
не забудь еще про кастомый хук автофокуса

2024-01-09 07:49 UTC, baklanovairina commented on src/components/UI/Button/Button.js
> +import styled from "styled-components";
а где сам компонент кнопки? Почему только стили?

2024-01-09 07:49 UTC, baklanovairina commented on src/components/UI/Header/Header.js
> +const Header = styled.header`
и здесь тоже, почему нет самого компонента?

2024-01-09 07:49 UTC, baklanovairina commented on src/components/UI/Input/index.jsx
> +  labelText,
я бы еще и label по умолчанию пустым задавала, т к он не всегда может быть

2024-01-09 07:49 UTC, baklanovairina commented on src/components/UI/Logo/Logo.js
> +const Logo = styled.img`
для лого отдельный компонент и стили? Это странно, если это не отделньный компонент, то зачем целый файл со стилями выделять этому, причем ради 1ой строки

2024-01-09 07:49 UTC, baklanovairina commented on src/helpers/validation.js
> +const stringPasswordValidation = (password) => {
почему Password? Эту функцию можно переиспользовать для любой строки

2024-01-09 07:49 UTC, baklanovairina commented on src/helpers/validation.js
> +const stringInputValidation = (login) => {
почему именно login? Здесь любая строка может быть

2024-01-09 07:49 UTC, baklanovairina commented on src/index.jsx
> +import { Provider } from 'react-redux';
порядок импортов нарушен

2024-01-09 07:49 UTC, baklanovairina commented on src/services/registration.js
> +import $api from "../http";
src/services/registration.js
не registration, ты же не будешь для каждой отдельной функции создавать отдельный файл
это будет файл user, т к здесь будут сервисы связанные только с юзерами

2024-01-09 07:49 UTC, baklanovairina commented on src/services/registration.js
> +  return await $api.post('/registration', { login, password });
а нужен ли здесь async/await, когда у тебя функция в 1 строку?

2024-01-09 07:49 UTC, baklanovairina commented on src/services/registration.js
> +const registrationRequest = async (login, password) => {
registrationRequest - переименуй, не используй в названии Request

2024-01-09 07:49 UTC, baklanovairina commented on src/store/actionCreators.js
> +import { MAKE_REGISTRATION } from "./actionTypes"
src/store/actionCreators.js - это не actionCreators, а actionTypes

2024-01-09 07:49 UTC, baklanovairina commented on src/store/actionCreators.js
> +    type: MAKE_REGISTRATION, payload
это объект, переноси свойства на новую строку, для лучшей читаемости

2024-01-09 07:49 UTC, baklanovairina commented on src/store/actionCreators.js
> +  }
а чего только 1? Как минимум 3 должно быть
стартовый - для очистки данных и подготовки запроса
успешный и неуспешный

2024-01-09 07:49 UTC, baklanovairina commented on src/store/actionTypes.js
> +export const MAKE_REGISTRATION = "MAKE_REGISTRATION";
src/store/actionTypes.js - а это больше enums, а не actionTypes

2024-01-09 07:49 UTC, baklanovairina commented on src/store/actionTypes.js
> +export const MAKE_REGISTRATION = "MAKE_REGISTRATION";
тоже 3 должно быть

2024-01-09 07:49 UTC, baklanovairina commented on src/store/asyncActions/registration.js
> +import registrationRequest from "../../services/registration";
не src/store/asyncActions, а actionCreators
и для всех actionCreators юзера один файл, а не для каждой функции разный

2024-01-09 07:49 UTC, baklanovairina commented on src/store/asyncActions/registration.js
> +export const registration = (errorCallback, login, password) => {
выше писала -  никаких errorCallback, только login, password

2024-01-09 07:49 UTC, baklanovairina commented on src/store/asyncActions/registration.js
> +  return async function(dispatch) {
стрелочная

2024-01-09 07:49 UTC, baklanovairina commented on src/store/asyncActions/registration.js
> +      errorCallback(error.response.data.message);
вот выше для обработки успешного результата у тебя makeRegistration
также нужно и для обработки неуспешного сделать и отправлять текст ошибки в компонент, где уже и происходит вывод ошибки, а не здесь

2024-01-09 07:49 UTC, baklanovairina commented on src/store/index.js
> +  registration: registrationReducer
не, для редьюсеров создается отдельная папка 
и в ней отдельный файл index, где подключаешь уже combineReducers
а здесь только создание стора

2024-01-09 07:49 UTC, baklanovairina commented on src/store/reducers/registrationReducer.js
> +      return { login: action.payload.login, password: action.payload.password }
перенос строк

и тоже будет минимум 3 case уже
и чтобы не расписывать каждое свойство (их может быть очень много) просто передай объект сразу, например
userData: action.payload,

2024-01-09 07:49 UTC, baklanovairina commented on src/store/reducers/registrationReducer.js
> +  password: ""
нет ошибки и свойства, отвечающего за проверку авторизованности
```
userData: {},
error: null,
isAuth: false,
```

2024-01-09 07:49 UTC, baklanovairina commented on vite.config.js
> +import { defineConfig } from 'vite'
vite.config.js ??
это зачем? Откуда взял такое?

2024-01-12 07:40 UTC, baklanovairina requested changes

2024-01-12 07:40 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +import Context from "../../../context";
порядок импортов

2024-01-12 07:40 UTC, baklanovairina commented on src/components/UI/Button/styles.js
> +    background-color: #C5E9FFB8;
а pointer есть?

2024-01-12 07:40 UTC, baklanovairina commented on src/constants.js
> +  "/registration": "Зарегистрироваться в системе"
почему это в константах? 
И я не нашла у тебя провайдер для контекста? 
Как ты отслеживаешь адресную строку и меняшь в зависимости от нее заголовок?

2024-01-12 07:40 UTC, baklanovairina commented on src/hooks/useAutoFocus.js
> +import { useRef, useEffect } from 'react'
;

2024-01-12 07:40 UTC, baklanovairina commented on src/hooks/useAutoFocus.js
> +  useEffect(() => inputRef.current.focus(), [])
;

2024-01-12 07:40 UTC, baklanovairina commented on src/index.jsx
> +      <Context.Provider value={headers[location.pathname]}>
вся магия а точнее логика контекста должна происходить в провайдере, а не здесь

2024-01-12 07:40 UTC, baklanovairina commented on src/store/actionTypes.js
> +      const response = await registrationApi(login, password);
тебе нужно придерживаться одной стилистики нейминга, чтобы было потом легко понять какая функция для какого функционала, т е например если мы говорим о регистрации, будет 
вместо clearDataBeforeAuth - startRegistration
вместо makeRegistration - registrationSuccess
вместо getWrongsAfterAuth - registrationError

и остальной функционал аналогично

2024-01-12 07:40 UTC, baklanovairina commented on src/store/actionTypes.js
> +export const registration = (login, password) => {
это actionCreators, в не actionTypes
поэтому выноси это отсюда

2024-01-12 07:40 UTC, baklanovairina commented on src/store/enums.js
> +export const GET_WRONGS_AFTER_AUTH = "GET_WRONGS_AFTER_AUTH";
здесь тоже нейминг поправить согласно комменту выше

2024-01-12 07:40 UTC, baklanovairina commented on vite.config.js
> +import { defineConfig } from 'vite'
так и не сказал почему ты взял библиотеку vite?

2024-01-12 10:33 UTC, VadimShkedov commented on vite.config.js
> +import { defineConfig } from 'vite'
у меня он почему то в .gitignore не добавляется

2024-01-15 08:27 UTC, baklanovairina requested changes

2024-01-15 08:27 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +  const location = useLocation();
а зачем он тебе здесь?

2024-01-15 08:27 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +        <h1>{header[location.pathname]}</h1>
location отслеживается в провайдере, а здесь уже просто header
иначе тебе везде придется его вызывать, а это уже дублирование

2024-01-15 08:27 UTC, baklanovairina commented on src/components/UI/Button/index.jsx
> +    <StyledButton onClick={handler}>
а type?

2024-01-15 08:27 UTC, baklanovairina commented on src/index.jsx
> +import GlobalStyle from "./globalStyles";
у тебя кавычки везде разные

2024-01-15 08:27 UTC, baklanovairina commented on src/store/actionCreators.js
> +      const response = await registrationApi(login, password);
registrationApi - переименуй хотя бы на registrationService

2024-01-16 06:24 UTC, baklanovairina commented on src/App.jsx
> +        <HeaderProvider>
а почему ты в App подключаешь провайдер, а не в index.js?

2024-01-16 06:24 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +  const handleButtonClick = async () => {
async?

2024-01-16 06:24 UTC, baklanovairina commented on src/components/UI/Button/index.jsx
> +    <StyledButton type="button" onClick={handler}>
не handler, а лучше либо actionButton либо handleClickButton
а то не очень понятно что за обработчик и для чего

2024-01-17 08:41 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +import Header from "../../UI/Header/styles";
а что тут стили Header забыли?

2024-01-17 08:41 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +  const header = useContext(Context);
ты в компоненте Header это вызови 1 раз и все, больше нигде не надо

2024-01-17 08:41 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +  const handleButtonClick = () => {
это не handleButtonClick, а как минимум валидация, а потом регистрация

2024-01-17 08:41 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +  const [formData, setFormData] = useState({
newUser

2024-01-17 08:41 UTC, baklanovairina commented on src/components/Pages/Registration/index.jsx
> +        <h1>{header}</h1>
h1 точно в компоненте Header должен быть

2024-01-17 08:41 UTC, baklanovairina commented on src/components/UI/Button/index.jsx
> +    <StyledButton type="button" onClick={handleClickButton}>
type это пропс

2024-01-17 08:41 UTC, baklanovairina commented on src/components/UI/Input/index.jsx
> +  inputHandler,
handleChangeInput

2024-01-19 16:19 UTC, merged